name: William DeMeo
markdown: kramdown
exclude:
  - "makefile"
  - ".gitlab-ci.yml"
  - "Gemfile"
  - "Gemfile.lock"
  - "*.agdai"
  - "*.lagda"
  - "*.agda"
  - "*.hs"
  - "*.hi"
  - "*.o"
  - "README.md"
  - "INSTALL.md"
  - "build"
  - "buildlocally"
  - "buildloop"
  - "fastloop"
  - "generatehtml"
  - "generatepdf"
  - "illiterate"
  - "illiterator"
  - "agdatomd"
  - "replace"
  - "slowloop"
  - "test"
  - "html/"
  - "ualib/"
  - "vendor/"
  - "ARCHIVE/"
  - "latex/"
  - "sphinx/"
  - "emacs/"
  - "jekyll/"
  - "src/"
  - "_site-prev/"
  - "_prev/"
